/*
   Copyright (c) 2009-2016, Jack Poulson
   All rights reserved.

   This file is part of Elemental and is under the BSD 2-Clause License,
   which can be found in the LICENSE file in the root directory, or at
   http://opensource.org/licenses/BSD-2-Clause
*/

/* NOTE: This is a commonly-used hack that is only included in this file to
         help avoid redundancy. */
#define INNER_IF_GUARD_AND_PAYLOAD(CDIST,RDIST,WRAP) \
  if( INNER_GUARD(CDIST,RDIST,WRAP) ) { INNER_PAYLOAD(CDIST,RDIST,WRAP) }

#define INNER_ELSEIF_GUARD_AND_PAYLOAD(CDIST,RDIST,WRAP) \
  else INNER_IF_GUARD_AND_PAYLOAD(CDIST,RDIST,WRAP)

#define IF_GUARD_AND_PAYLOAD(CDIST,RDIST,WRAP) \
  if( GUARD(CDIST,RDIST,WRAP) ) \
  { \
      PAYLOAD(CDIST,RDIST,WRAP) \
      INNER_IF_GUARD_AND_PAYLOAD(    Dist::CIRC,Dist::CIRC,DistWrap::ELEMENT) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::MC,  Dist::MR  ,DistWrap::ELEMENT) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::MC,  Dist::STAR,DistWrap::ELEMENT) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::MD,  Dist::STAR,DistWrap::ELEMENT) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::MR,  Dist::MC  ,DistWrap::ELEMENT) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::MR,  Dist::STAR,DistWrap::ELEMENT) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::MC  ,DistWrap::ELEMENT) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::MD  ,DistWrap::ELEMENT) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::MR  ,DistWrap::ELEMENT) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::STAR,DistWrap::ELEMENT) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::VC  ,DistWrap::ELEMENT) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::VR  ,DistWrap::ELEMENT) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::VC,  Dist::STAR,DistWrap::ELEMENT) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::VR,  Dist::STAR,DistWrap::ELEMENT) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::CIRC,Dist::CIRC,DistWrap::BLOCK) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::MC,  Dist::MR  ,DistWrap::BLOCK) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::MC,  Dist::STAR,DistWrap::BLOCK) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::MD,  Dist::STAR,DistWrap::BLOCK) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::MR,  Dist::MC  ,DistWrap::BLOCK) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::MR,  Dist::STAR,DistWrap::BLOCK) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::MC  ,DistWrap::BLOCK) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::MD  ,DistWrap::BLOCK) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::MR  ,DistWrap::BLOCK) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::STAR,DistWrap::BLOCK) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::VC  ,DistWrap::BLOCK) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::VR  ,DistWrap::BLOCK) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::VC,  Dist::STAR,DistWrap::BLOCK) \
      INNER_ELSEIF_GUARD_AND_PAYLOAD(Dist::VR,  Dist::STAR,DistWrap::BLOCK) \
  }

#define ELSEIF_GUARD_AND_PAYLOAD(CDIST,RDIST,WRAP) \
  else IF_GUARD_AND_PAYLOAD(CDIST,RDIST,WRAP)

IF_GUARD_AND_PAYLOAD(    Dist::CIRC,Dist::CIRC,DistWrap::ELEMENT)
ELSEIF_GUARD_AND_PAYLOAD(Dist::MC,  Dist::MR  ,DistWrap::ELEMENT)
ELSEIF_GUARD_AND_PAYLOAD(Dist::MC,  Dist::STAR,DistWrap::ELEMENT)
ELSEIF_GUARD_AND_PAYLOAD(Dist::MD,  Dist::STAR,DistWrap::ELEMENT)
ELSEIF_GUARD_AND_PAYLOAD(Dist::MR,  Dist::MC  ,DistWrap::ELEMENT)
ELSEIF_GUARD_AND_PAYLOAD(Dist::MR,  Dist::STAR,DistWrap::ELEMENT)
ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::MC  ,DistWrap::ELEMENT)
ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::MD  ,DistWrap::ELEMENT)
ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::MR  ,DistWrap::ELEMENT)
ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::STAR,DistWrap::ELEMENT)
ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::VC  ,DistWrap::ELEMENT)
ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::VR  ,DistWrap::ELEMENT)
ELSEIF_GUARD_AND_PAYLOAD(Dist::VC,  Dist::STAR,DistWrap::ELEMENT)
ELSEIF_GUARD_AND_PAYLOAD(Dist::VR,  Dist::STAR,DistWrap::ELEMENT)
ELSEIF_GUARD_AND_PAYLOAD(Dist::CIRC,Dist::CIRC,DistWrap::BLOCK)
ELSEIF_GUARD_AND_PAYLOAD(Dist::MC,  Dist::MR  ,DistWrap::BLOCK)
ELSEIF_GUARD_AND_PAYLOAD(Dist::MC,  Dist::STAR,DistWrap::BLOCK)
ELSEIF_GUARD_AND_PAYLOAD(Dist::MD,  Dist::STAR,DistWrap::BLOCK)
ELSEIF_GUARD_AND_PAYLOAD(Dist::MR,  Dist::MC  ,DistWrap::BLOCK)
ELSEIF_GUARD_AND_PAYLOAD(Dist::MR,  Dist::STAR,DistWrap::BLOCK)
ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::MC  ,DistWrap::BLOCK)
ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::MD  ,DistWrap::BLOCK)
ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::MR  ,DistWrap::BLOCK)
ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::STAR,DistWrap::BLOCK)
ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::VC  ,DistWrap::BLOCK)
ELSEIF_GUARD_AND_PAYLOAD(Dist::STAR,Dist::VR  ,DistWrap::BLOCK)
ELSEIF_GUARD_AND_PAYLOAD(Dist::VC,  Dist::STAR,DistWrap::BLOCK)
ELSEIF_GUARD_AND_PAYLOAD(Dist::VR,  Dist::STAR,DistWrap::BLOCK)

#undef ELSEIF_GUARD_AND_PAYLOAD
#undef IF_GUARD_AND_PAYLOAD
#undef INNER_PAYLOAD
#undef INNER_GUARD
#undef GUARD
#undef PAYLOAD
